spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_boot_test?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC

  #config JPA
  jpa:
    hibernate:
      ddl-auto: create #update or create table
    show-sql: true #show the sql on the console

server:
  port: 8080

management.endpoints.web.exposure.include: "*" #暴露数据 以便后续监控
