spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_boot_test?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC

  #config JPA
  jpa:
    hibernate:
      ddl-auto: create #update or create table
    show-sql: true #show the sql on the console

#email
  mail:
    host: smtp.aliyun.com
    username: chekyyao@aliyun.com
    password: "*****************"
    port: 25
    #设置为SSL协议
    #properties.mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
    #properties.from: chekyyao@aliyun.com

#redis 启动服务 redis-server.exe redis.windows.conf
  redis:
    host: localhost
    port: 6379
    password: 123456 #配置密码 https://jingyan.baidu.com/article/86fae3466be4bc7c49121abf.html
    jedis:
      pool:
        max-active: 500
        max-idle: 1000
        max-wait: 6000ms
        min-idle: 4

server:
  port: 8084

management.endpoints.web.exposure.include: "*" #暴露数据 以便后续监控

jwt:
  secret: JO6HN3NGIU25G2FIG8V7VD6CK9B6T2Z5 #服务端的秘钥
  expire: 15 #多少秒后过期

#jwt
jwt2:
  header: Authorization
  # 令牌前缀
  token-start-with: Bearer
  # 使用Base64对该令牌进行编码
  base64-secret: L3Nob3BwaW5nL2NvbmZpcm0uYWN0aW9uP2lkPTEmbmFtZT1pdHpoYWkYWN0aW9uP2lkPTEmbmFtZT1pdHpoYWk=
  # 令牌过期时间 此处单位/毫秒
  token-validity-in-seconds: 14400000

#name-server
rocketmq:
  name-server: localhost:9876
  producer:
    group: mygroup
  consumer:
    group: mygroup

#配置 fdfs
fdfs:
  so-timeout: 2001
  connect-timeout: 601
  thumb-image:
    width: 60
    height: 60
  tracker-list:
    - 10.3.0.166:22122 #连接已部署tracker server的IP和Port