spring:
  application:
    name: user-service
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/spring_boot_test?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
  jpa:
    #database-platform: org.hibernate.dialect.MySQLDialect # 使用后DAO会运行异常
    hibernate:
      ddl-auto: create #update or create table
    show-sql: true #show the sql on the console


dubbo:
  application.name: ${spring.application.name}
  scan.basePackages: com.cheky
  registry:
    address: nacos://127.0.0.1:8848
  protocol:
    name: dubbo
    port: 20885